---
title: Goldhirsh Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    excerpt: ''
    author: ''
    categories: blog
    layout: post
description: The Goldhirsh Foundation connects the dots between the best emerging
  innovations and the financial, social, and human capital to make them thrive.
image: https://goldhirshfoundation.org/assets/img/logotype-square.png
exclude:
- README
- CNAME
- Gemfile
- Gemfile.lock
permalink: pretty
version: 0.0.4
